= Config-files

A backup of my different configuration files and a way to easily and quickly install my work environment on Debian-based distributions.

== Targeted software

* https://github.com/alacritty/alacritty[Alacritty]
* https://www.gnu.org/software/bash/[Bash]
* https://www.gtk.org/[GTK]
* https://neovim.io/[Neovim]
* http://jonls.dk/redshift/[Redshift]
* https://github.com/davatorium/rofi[Rofi]
* https://www.x.org/releases/X11R7.6/doc/man/man1/xdm.1.xhtml[XDM]
* https://xmobar.org/[Xmobar]
* https://xmonad.org/[Xmonad]
* https://wiki.debian.org/Xsession[Xsession]

== Installation

To install my work environment run the following command in the root folder of the repository. Before, make sure you don't want to keep your current configuration files.
[source, shell]
----
make install
----

== Update

To update all the installed packages, you can run the following command.
[source, shell]
----
update
----

== Misc.

* To add a usb group in Debian run  the `usb_group_debian.sh` script as the superuser.
* Modify the first line of `.xsession` to indicate the path of your wallpaper.
* To connect to a Wi-Fi network use `nmtui` or `nmcli`. For https://www.eduroam.org/[eduroam] use the https://cat.eduroam.org/[eduroam Configuration Assistant Tool]
* To change the keyboard layout run `sudo dpkg-reconfigure keyboard-configuration` (and don't forget to enable `Use system keyboard layout` in the advanced menu of `ibus-setup`).
* Take a look at `monitors-help.adoc` to modify the settings of your monitors.
* To allow Network Manager to work with every interface, please set `managed` to true in `/etc/NetworkManager/NetworkManager.conf`
* To configure Plymouth please take a look at https://wiki.debian.org/plymouth[plymouth - Debian Wiki]

== License

Public domain.
