= Config-files

A backup of my different configuration files and a way to easily and quickly install my work environment on Debian-based distributions.

== Targeted software

* https://github.com/alacritty/alacritty[Alacritty]
* https://www.gnu.org/software/bash/[Bash]
* https://clang.llvm.org/docs/ClangFormat.html[ClangFormat]
* https://www.gtk.org/[GTK]
* http://jonls.dk/redshift/[Redshift]
* https://wiki.debian.org/Xsession[Xsession]

== Installation

To install my work environment run the following command in the root folder of the repository. Before, make sure you don't want to keep your current configuration files.
[source, shell]
----
make install
----

== Update

To update all the installed packages, you can run the following command.
[source, shell]
----
update
----

== Misc.

* To add a usb group in Debian run  the `usb_group_debian.sh` script as the superuser.
* Modify the first line of `.xsession` to indicate the path of your wallpaper.
* To change the keyboard layout run `sudo dpkg-reconfigure keyboard-configuration` (`Generic 105-key PC`, `English (US) - English (intl., with AltGr dead keys)`, `The default for the keyboard layout`, `Right Alt (AltGr)`).
* Take a look at `monitors-help.adoc` to modify the settings of your monitors.
* To allow Network Manager to work with every interface, please set `managed` to true in `/etc/NetworkManager/NetworkManager.conf`
* Check if network interface defined in /etc/network/interfaces

== License

Public domain.
